### ISSUE TITLE
Error when logging in and when reporting bug you are basically stuck in GitHub

### ISSUE THREAD

**Issue by MaketendoDev** [Smithed-MC/UX#60]
"Unexpected token '<', "<!DOCTYPE "... is not valid JSON
Trace
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON" is the error you get and also you have to restart when going back from GitHub on the app

**Comment by MaketendoDev** [comment]
just found out this error also appears when browsing too

**Comment by MaketendoDev** [comment]
<details><summary>Details</summary>
<p>

bug

</p>
</details>

**Comment by bbfh-dev** [comment]
Can you write more details about the issue? Specifically about how to reproduce it step-by-step
